name: Reset archive list
on:
  workflow_dispatch:
    inputs:
      rawsource:
        description: 'rclone ls output (.raw) file to be used for generating new lists'
        required: true
        default: 'generated/s3-only.raw'

jobs:
  getpkgs:
    container:
      image: rclone/rclone:latest
    name: Generate lists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          bash list-scripts/rclonels_to_list.sh ${{ github.event.inputs.rawsource }} 8000000000 200 lists/archive2
          bash generate_todo.sh archive2 todo.txt
